### ISSUE TITLE
exp_anomaly_detection.py

### ISSUE THREAD

**Issue by bxdgl** [YHYHYHYHYHY/ATFNet#6]
hi， 
   Thanks to the valuable work of the author, can you provide anomaly detection scripts：）

**Comment by YHYHYHYHYHY** [comment]
Thank you for recognizing our work. While we appreciate your interest, the model we developed is specifically designed for forecasting tasks and is not intended for anomaly detection.  I would recommend exploring other anomaly detection models and techniques that are specifically tailored for addressing your needs.
