### ISSUE TITLE
Run the model in Macbook Pro

### ISSUE THREAD

**Issue by Yamazaki85** [YHYHYHYHYHY/ATFNet#7]
Hi, 
Would you please advise whether I can run the model on a MacOS? I cannot install CUDA and not sure what to do next. 
Also, where can I get the datasets you used for the model? Any help i sgreatly appreciated. Thanks

**Comment by YHYHYHYHYHY** [comment]
In general, Macs do not come with NVIDIA GPUs pre-installed. Apple has transitioned to using their own custom-designed Apple Silicon chips, which have integrated Apple GPUs. These Apple GPUs are not compatible with NVIDIA CUDA or other NVIDIA-specific technologies. In most cases, we do not run deep model training directly on the computing resources of a macos machine. I suggest that you look for a remote server with NVIDIA GPUs installed and run the experiments on the server.

As for the datasets, the informations and links are included in the Time-Series-Library (https://github.com/thuml/Time-Series-Library), and you can download all datasets included in our experiments following the instructions.
