### ISSUE TITLE
ComplexLayers.py The product of two complex tensors should not be calculated using +

### ISSUE THREAD

**Issue by lllzzz3** [YHYHYHYHYHY/ATFNet#8]
I think change 

def complex_mul(order, mat1, mat2):  
    return (torch.einsum(order, mat1.real, mat2.real) - torch.einsum(order, mat1.imag, mat2.imag)) \
        + 1j * (torch.einsum(order, mat1.real, mat2.imag) - torch.einsum(order, mat1.imag, mat2.real))

into

def complex_mul(order, mat1, mat2):  
    return (torch.einsum(order, mat1.real, mat2.real) - torch.einsum(order, mat1.imag, mat2.imag)) \
        + 1j * (torch.einsum(order, mat1.real, mat2.imag) + torch.einsum(order, mat1.imag, mat2.real))

**Comment by YHYHYHYHYHY** [comment]
Thank you for bringing this issue to our attention. We are pleased to inform you that the bug in the code has been successfully fixed.
